name: Create Release

on:
  push:
    branches:
      - master

jobs:
  test:
    name: Test
    runs-on: macos-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Test Package
      run: swift test -v
    - name: Build Release
      run: swift build -c release
  bump-tag-and-create-release:
    name: Bump tag and create release
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DEFAULT_BUMP: patch
      id: bump_version
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.bump_version.outputs.tag}}
        release_name: ${{ steps.bump_version.outputs.tag }}
