name: Test PR

on: [pull_request]

jobs:
  SwiftLint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: SwiftLint
        uses: norio-nomura/action-swiftlint@3.0.1

  Test:
    runs-on: macos-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Run tests
      run: swift test -v
